language: go
go:
- '1.9'
- '1.10'
script:
  # from https://docs.coveralls.io/go
  - GO_TEST_ARGS="-coverprofile=coverage.out" make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
before_install:
- go get golang.org/x/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
notifications:
  email: false
env:
  global:
    secure: RNl3sjx+2PC7AgUYoN5XSnxixnkcDqU61n/PhETnvSQXpWwmFCMZDKTHsMAPBzQUjEz01Qu13TseCrwipJoH/izma702OJUbVZklpdocAwvRDHUWdDS8RxaRHSnj7vqqVeI8GDRPvLuTgW6Ej7iRSKERPJvFl/0GGYGLGgtuKKc+++44xFuvoSgaetiAqSGBZHZWWwQFB6bETHAGyM/PRLcKzl7uwa2Rfn8ZCZKN7nQoQ4cVILMJmtm8q3Q2k+238KsaOsPfBgAe6o2EJwNYS6F4QuQwN1wuQyxgzHO4PcqHzukZsYKmzkWolEmHRgSsy0MDTurnchd6GYym4A2f2ztdyqLrHyTvrOEflrY/O39U8f36nwMpdqZM3ZH5zghv+CJSEvVEF1mJbPX3PwYk7dx332XmA9EB5c8H7aJBRp/2YJWkVwvZlvPw7jZx2aH4H9I9Au2b0Axk2bAJeJ29Ooeqb6DmjZtSb03FG0DHOINT+Y00oDTZBE8G6FUJvRvAFmSxN/Gdz8XAB6QJMSw7AJWlOZkPJDdpmdPRIdQZ1LkFftUFooyv+SxyCq4LjcLgPciPVGUP0JCE2m05IgVNENdgLfT6tMD8VVphcgk+yQJWJkfZEz58FT1rKsmG8kW63OvCJHgk0mfcjwV6HVON/bM8xMRCguiNpk70q0ar8a4=
